# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='ref',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
