# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    replaces = [('pages', '0005_snippet'), ('pages', '0006_auto_20170626_2204'), ('pages', '0007_auto_20170627_1417'), ('pages', '0008_snippet_img'), ('pages', '0009_auto_20170627_1903'), ('pages', '0010_auto_20170627_1908'), ('pages', '0011_auto_20170627_1911')]

    dependencies = [
        ('pages', '0004_auto_20170622_1804'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.IntegerField()),
                ('top', models.IntegerField()),
                ('left', models.IntegerField()),
                ('bottom', models.IntegerField()),
                ('right', models.IntegerField()),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Attachment')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='pages.GenericStringTaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('text', models.CharField(blank=True, default='', max_length=2048)),
                ('url', models.CharField(blank=True, default='', max_length=256)),
                ('name', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
    ]
