# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 23:02
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_snippet_squashed_0011_auto_20170627_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='pages.GenericStringTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
